"""
Constructed examples for the sub-types real data does not supply 50 of.

RULES I HELD MYSELF TO WHILE WRITING THESE:

1. **The claim is always real.** Every claim below is one of the 84 distinct
   claims in the Phase 3 + Phase 4A corpora. Inventing both halves lets an
   author choose the test as well as the answer, which is how a taxonomy ends
   up describing its own author.
2. **One premise per example**, wherever possible, so a label is unambiguous
   about what it is labelling.
3. **No question is written to be easy.** Several are deliberately near the
   boundary, and those are flagged `contested` rather than quietly dropped —
   the items a rule cannot decide are the finding, not the noise.
4. **These prove nothing quantitative.** They are specification material. No
   precision, recall or frequency figure in the report rests on them.
"""

from __future__ import annotations

# (claim, question, note)
SPECIFICALLY_UNENTAILED: list[tuple[str, str, str]] = [
    ("Cut p95 latency from 900ms to 180ms.",
     "What specific actions did you take in New Relic to bring p95 down?",
     "named vendor; latency work implies no particular APM"),
    ("Built REST APIs on Postgres and deployed to Kubernetes on AWS.",
     "How did you use the service mesh to route traffic during deploys?",
     "a service mesh is one deployment choice among several"),
    ("Wrote the reconciliation service in Java against a Postgres database.",
     "What steps did you take in the feature-flag system before each release?",
     "feature flags are optional for a batch reconciliation service"),
    ("Frontend developer building React interfaces against internal APIs.",
     "What specific actions did you take in Storybook each day?",
     "named vendor; React work implies no component workshop"),
    ("Owned the deploy tooling and improved throughput of the ingestion service fourfold.",
     "How did you use the canary dashboard to decide when to roll back?",
     "a canary dashboard is a mechanism inside a deploy strategy"),
    ("Reduced reopen rate by a third.",
     "What steps did you take in the auto-triage rules each week?",
     "auto-triage is one mechanism; reopen rate implies none"),
    ("Managed a support team of 12 covering chat support and email support for an e-commerce platform.",
     "What actions did you take in the chatbot builder to deflect tickets?",
     "deflection is not claimed and a bot is optional"),
    ("Led the escalation desk for a SaaS product.",
     "How did you use the war-room bridge to coordinate P1s?",
     "one coordination mechanism among many"),
    ("Cut first response time from 9 hours to under 2.",
     "What specific steps did you take in the SLA timer configuration each morning?",
     "a configuration screen inside a category, not the category"),
    ("Took escalation from tier 1 and tracked resolution time week over week.",
     "What actions did you perform in the knowledge base editor?",
     "a knowledge base is not entailed by taking escalations"),
    ("Customer success manager for 60 enterprise accounts, working mostly out of Freshdesk and email support.",
     "How did you use Gainsight to score account health?",
     "named vendor, and the claim names a DIFFERENT tool"),
    ("Ran the chat support queue.",
     "What steps did you take in the sentiment analysis tool during peak hours?",
     "sentiment analysis is optional for running a queue"),
    ("Wrote macros for the top ten issue types.",
     "How did you use the A/B testing tool to compare macro versions?",
     "A/B testing macros is one practice of many"),
    ("Owned resolution time for P1 issues.",
     "How did you use the customer-facing status page to manage P1s?",
     "a public status page is a choice, not a requirement"),
    ("Managed a team of 22 agents and ran the daily huddle",
     "What specific actions did you take in the gamification platform each week?",
     "gamification is not entailed by running a huddle"),
    ("Ran weekly calibration with the quality team",
     "How did you use the speech analytics engine during calibration?",
     "calibration is commonly manual"),
    ("Owned shrinkage and abandon rate for a 200-seat call centre in Gurgaon.",
     "What steps did you take in the biometric attendance terminal each shift?",
     "one specific attendance mechanism"),
    ("Managed nesting batches for new hires on a night shift voice process before they moved to the production floor.",
     "What actions did you take in the LMS quiz builder during nesting?",
     "a quiz builder is a mechanism inside an LMS, itself optional"),
    ("Held SLA attainment at 97% across four queues by rebuilding the roster model",
     "How did you use the Erlang calculator each morning?",
     "one specific staffing method"),
    ("Improved CSAT from 78% to 92% in four quarters by redesigning the escalation workflow",
     "What did you do in the survey tool's branching logic?",
     "branching logic is a mechanism two levels inside the category"),
    ("Drove a 30% improvement in CSAT scores across the entire process",
     "What actions did you take in the coaching tracker to lift CSAT?",
     "an instrument bolted to an OUTCOME, not to a performed activity"),
    ("Delivered a 30% improvement in AHT through advanced process optimisation",
     "How did you use the process mining tool to find the AHT savings?",
     "process mining is one method; the claim implies none"),
    ("Brought AHT down from 8 minutes to 5 and kept occupancy above 85%.",
     "What steps did you take in the screen-recording tool to cut AHT?",
     "screen recording is optional"),
    ("Ran workforce planning for a 24x7 contact centre.",
     "How did you use the shift-swap mobile app each week?",
     "a mechanism inside a WFM category that IS entailed"),
    ("Built a sourcing team of six and cut attrition in the first 90 days by half.",
     "What actions did you take in the exit-interview analytics module to cut attrition?",
     "instrument bolted to an outcome, and a module inside a category"),
    ("HRBP for a 400-person org.",
     "What steps did you take in the engagement pulse tool each month?",
     "an HRBP need not run pulse surveys"),
    ("Recruiter hiring for engineering roles. Sourcing on Naukri and Shine, managed offer rollout and joinee follow-up.",
     "How did you use LinkedIn Recruiter to build pipelines?",
     "named vendor, and the claim names two DIFFERENT sourcing channels"),
    ("Ran interview panels and reduced time to offer from 40 days to 22.",
     "What did you do in the interview scorecard calibration screen?",
     "a specific screen inside an ATS"),
    ("HR generalist handling payroll, onboarding and exit formalities for two business units.",
     "How did you use the org-chart visualisation tool during onboarding?",
     "optional category"),
    ("Led campus hiring, sourcing, interview coordination and joinee onboarding for 120 offers.",
     "What actions did you take in the video interview platform for campus rounds?",
     "campus rounds are frequently in person"),
    ("Coached four inside sales reps on closing technique",
     "How did you use the call recording software to coach?",
     "coaching is commonly live; recording is one method"),
    ("Closed 34 deals last year.",
     "What steps did you take in the e-signature tool for each close?",
     "a mechanism at the end of a close, not the close"),
    ("Grew ARR from $400K to $1.1M",
     "How did you use the revenue intelligence platform to grow ARR?",
     "instrument bolted to an outcome"),
    ("Ran the deal desk.",
     "What did you do in the discount heat-map dashboard each day?",
     "a specific view inside a CPQ/CRM category"),
    ("Built pipeline through outbound prospecting and closed 34 deals last year.",
     "How did you use the sales engagement sequencer daily?",
     "sequencing software is one prospecting method"),
    ("Ran 40 user interviews to find the top three pain points before writing the PRD",
     "What did you do in the research repository's tagging view?",
     "a view inside a repository, itself optional"),
    ("Ran a/b tests on the cart flow and lifted adoption of saved cards by 18%.",
     "How did you use the session replay tool during the test?",
     "session replay is optional for an A/B test"),
    ("Tracked adoption after launch.",
     "What actions did you take in the in-app messaging tool to drive adoption?",
     "instrument bolted to an outcome the claim only observes"),
    ("Built dashboards in Tableau and Power BI on top of a Snowflake warehouse.",
     "How did you use dbt tests to validate the dashboards?",
     "named tool absent from a claim that names three others"),
    ("Wrote SQL against the data warehouse to produce weekly reporting for the operations group.",
     "What steps did you take in the query scheduler's alerting rules?",
     "alerting rules are a mechanism inside a scheduler"),
    ("Re-engineered the intake process and delivered rapid improvements in turnaround time.",
     "How did you use the BPMN modelling tool during the re-engineering?",
     "process redesign rarely requires formal BPMN tooling"),
]

INVENTED_EVENT: list[tuple[str, str, str]] = [
    ("Managed a team of 35 agents across 4 pods with 4 senior associates reporting to me",
     "How did you handle the walkout in the second pod?", "definite episode, never claimed"),
    ("Ran the chat support queue.",
     "What did you do during the outage that took chat down?", "definite outage"),
    ("Cut first response time from 9 hours to under 2.",
     "How did you recover after the backlog spike in December?", "definite month and spike"),
    ("Owned CASA growth, daily reconciliation and audit compliance for a metro branch.",
     "What did you decide during the audit finding on reconciliation?", "an audit FINDING is asserted"),
    ("Processed insurance claims and mutual fund transactions at a bank's back office in Mumbai.",
     "How did you handle the settlement failure that quarter?", "definite failure"),
    ("Ran KYC audits and reported exceptions to the risk committee.",
     "What did you do about the regulator's adverse observation?", "definite regulatory action"),
    ("Built REST APIs on Postgres and deployed to Kubernetes on AWS.",
     "How did you respond to the production incident after the schema migration?",
     "two invented events, an incident and a migration"),
    ("Cut p95 latency from 900ms to 180ms.",
     "What did you change after the latency regression shipped?", "a regression is asserted"),
    ("Owned the deploy tooling and improved throughput of the ingestion service fourfold.",
     "How did you handle the failed rollout that blocked the release train?", "definite failure"),
    ("Ran interview panels and reduced time to offer from 40 days to 22.",
     "What did you do when the offer freeze hit mid-quarter?", "definite freeze"),
    ("Led campus hiring, sourcing, interview coordination and joinee onboarding for 120 offers.",
     "How did you manage the campus that cancelled its slot?", "definite cancellation"),
    ("Grew ARR from $400K to $1.1M",
     "What did you do after losing the anchor account?", "a loss asserted against a growth claim"),
    ("Ran the deal desk.",
     "How did you handle the pricing escalation from the regional VP?", "definite escalation and person"),
    ("Deprioritised two epics to ship the MVP a quarter early.",
     "What did you decide during the scope fight with engineering?", "definite conflict"),
    ("Ran discovery interviews with branch staff.",
     "How did you respond when the branch manager blocked access?", "definite obstruction"),
    ("Managed rosters for 42 agents across three shifts",
     "What did you do about the shift clash over the festival week?", "definite week and clash"),
    ("Handled vendor coordination, invoice follow-up and the daily MIS for the regional office.",
     "How did you resolve the payment dispute with the vendor?", "definite dispute"),
]

INVENTED_METRIC: list[tuple[str, str, str]] = [
    ("Managed a team of 22 agents and ran the daily huddle",
     "How do you calculate your team's schedule adherence?", "adherence never claimed"),
    ("Ran the chat support queue.",
     "How was your concurrency rate measured?", "concurrency never claimed"),
    ("Led the escalation desk for a SaaS product.",
     "How did you define your escalation leakage rate?", "leakage rate never claimed"),
    ("Wrote macros for the top ten issue types.",
     "How did you measure macro deflection rate?", "deflection never claimed"),
    ("Customer success manager for 60 enterprise accounts, working mostly out of Freshdesk and email support.",
     "How did you compute net revenue retention for your book?", "NRR never claimed"),
    ("Managed a support team of 12 covering chat support and email support for an e-commerce platform.",
     "How did you define your one-touch resolution rate?", "one-touch never claimed"),
    ("Owned CASA growth, daily reconciliation and audit compliance for a metro branch.",
     "How did you measure your branch's cost-to-income ratio?", "a P&L metric, not an ops one"),
    ("Loan operations executive. Handled disbursement checks, credit memos and monthly reconciliation.",
     "How did you track first-pass yield on disbursement files?", "FPY never claimed"),
    ("Reviewed loan files for underwriting and cleared KYC exceptions before disbursement.",
     "How did you measure your exception recurrence rate?", "recurrence never claimed"),
    ("Worked in NPA recovery for a housing finance company, coordinating with legal on more than 300 accounts.",
     "How did you calculate your roll-rate each month?", "roll-rate never claimed"),
    ("Built ETL pipelines with dbt and Airflow, and maintained the reporting layer in SQL.",
     "How did you measure pipeline freshness?", "freshness never claimed"),
    ("Data engineer. Airflow DAGs, dbt models and a warehouse feeding Tableau extracts.",
     "How did you define your DAG failure rate?", "failure rate never claimed"),
    ("Wrote SQL against the data warehouse to produce weekly reporting for the operations group.",
     "How did you measure query cost per report?", "cost per report never claimed"),
    ("Trained a demand forecast model and took it to production.",
     "How did you track the model's population stability index?", "PSI never claimed"),
    ("Frontend developer building React interfaces against internal APIs.",
     "How did you measure your Core Web Vitals?", "CWV never claimed"),
    ("Built event pipelines on Kafka and Redis, running as microservices behind an API gateway.",
     "How did you define your event loss rate?", "loss rate never claimed"),
    ("Wrote the reconciliation service in Java against a Postgres database.",
     "How did you measure break rate on reconciliation?", "break rate never claimed"),
    ("HR generalist handling payroll, onboarding and exit formalities for two business units.",
     "How did you measure payroll accuracy rate?", "accuracy rate never claimed"),
    ("HRBP for a 400-person org.",
     "How did you calculate your span-of-control ratio?", "span of control never claimed"),
    ("Sourcing on Naukri and Shine, managed offer rollout and joinee follow-up.",
     "How did you track your source-of-hire mix?", "mix never claimed"),
    ("Owned the recruiting funnel from sourcing through offer rollout.",
     "How did you measure candidate NPS?", "candidate NPS never claimed"),
    ("Built the experiment backlog and instrumented activation events across the funnel.",
     "How did you define your experiment velocity?", "velocity never claimed"),
    ("Ran 18 experiments against a single north star metric, 5 of which shipped",
     "How did you measure time-to-decision on each experiment?", "TTD never claimed"),
    ("Tracked adoption after launch.",
     "How did you measure day-30 retention?", "a different measure from adoption"),
    ("Consistently at 110% of target with a conversion rate of 22% from qualified leads.",
     "How did you measure average deal cycle length?", "cycle length never claimed"),
    ("Owned a pipeline of 80 prospects and hit quota six quarters running.",
     "How did you measure your logo churn?", "churn never claimed"),
]

INVENTED_ARTEFACT: list[tuple[str, str, str]] = [
    ("Managed a team of 35 agents across 4 pods with 4 senior associates reporting to me",
     "What did you include in the weekly business review deck?", "a deck is never claimed"),
    ("Managed rosters for 42 agents across three shifts",
     "How did you structure the shrinkage forecast document?", "document never claimed"),
    ("Ran weekly calibration with the quality team",
     "What went into the calibration charter?", "charter never claimed"),
    ("Ran workforce planning for a 24x7 contact centre.",
     "How did you build the capacity plan sign-off memo?", "memo never claimed"),
    ("Owned shrinkage and abandon rate for a 200-seat call centre in Gurgaon.",
     "What did the shrinkage RCA report cover?", "RCA report never claimed"),
    ("Improved CSAT from 78% to 92% in four quarters by redesigning the escalation workflow",
     "What was in your CSAT improvement roadmap?", "roadmap never claimed"),
    ("Held SLA attainment at 97% across four queues by rebuilding the roster model",
     "How did you structure the roster model design document?", "design document never claimed"),
    ("Brought AHT down from 8 minutes to 5 and kept occupancy above 85%.",
     "What did the AHT reduction business case contain?", "business case never claimed"),
    ("Managed a team of 45 agents and consistently exceeded all CSAT targets",
     "What did you put in the quarterly appraisal template?", "template never claimed"),
    ("Managed nesting batches for new hires on a night shift voice process before they moved to the production floor.",
     "How did you write the nesting exit criteria document?", "document never claimed"),
    ("Reduced reopen rate by a third.",
     "What did the reopen postmortem write-up conclude?", "write-up never claimed"),
    ("Cut first response time from 9 hours to under 2.",
     "What was in the first-response runbook?", "runbook never claimed"),
    ("Led the escalation desk for a SaaS product.",
     "How did you write the P1 escalation matrix?", "matrix never claimed"),
    ("Ran the chat support queue.",
     "What did the chat staffing proposal recommend?", "proposal never claimed"),
    ("Took escalation from tier 1 and tracked resolution time week over week.",
     "What went into the tier-1 deflection playbook?", "playbook never claimed"),
    ("Wrote macros for the top ten issue types.",
     "What did the macro style guide specify?", "style guide never claimed"),
    ("Customer success manager for 60 enterprise accounts, working mostly out of Freshdesk and email support.",
     "How did you build each account's success plan?", "success plan never claimed"),
    ("Managed a support team of 12 covering chat support and email support for an e-commerce platform.",
     "What did the support coverage SOP say?", "SOP never claimed"),
    ("Owned resolution time for P1 issues.",
     "What did you include in the P1 postmortem template?", "template never claimed"),
    ("Ran KYC audits and reported exceptions to the risk committee.",
     "How did you draft the KYC remediation plan?", "remediation plan never claimed"),
    ("Reviewed loan files for underwriting and cleared KYC exceptions before disbursement.",
     "What did the credit policy exception note contain?", "note never claimed"),
    ("Loan operations executive. Handled disbursement checks, credit memos and monthly reconciliation.",
     "How did you prepare the disbursement checklist?", "checklist never claimed"),
    ("Owned CASA growth, daily reconciliation and audit compliance for a metro branch.",
     "What did the branch growth plan commit to?", "plan never claimed"),
    ("Processed insurance claims and mutual fund transactions at a bank's back office in Mumbai.",
     "What was in the claims quality manual?", "manual never claimed"),
    ("Worked in NPA recovery for a housing finance company, coordinating with legal on more than 300 accounts.",
     "What did the recovery dashboard specification require?", "specification never claimed"),
    ("Built ETL pipelines with dbt and Airflow, and maintained the reporting layer in SQL.",
     "What did the data contract document specify?", "data contract never claimed"),
    ("Built dashboards in Tableau and Power BI on top of a Snowflake warehouse.",
     "What did the dashboard style guide mandate?", "style guide never claimed"),
    ("Data engineer. Airflow DAGs, dbt models and a warehouse feeding Tableau extracts.",
     "How did you write the data lineage catalogue?", "catalogue never claimed"),
    ("Owned the SQL reporting stack and a Looker dashboard suite for the commercial team.",
     "What was in the metrics definition glossary?", "glossary never claimed"),
    ("Trained a demand forecast model and took it to production.",
     "What did the model card record?", "model card never claimed"),
    ("Wrote SQL against the data warehouse to produce weekly reporting for the operations group.",
     "What did the reporting requirements document ask for?", "requirements doc never claimed"),
    ("Built REST APIs on Postgres and deployed to Kubernetes on AWS.",
     "What did the API design RFC propose?", "RFC never claimed"),
    ("Cut p95 latency from 900ms to 180ms.",
     "What did the performance test plan cover?", "test plan never claimed"),
    ("Built event pipelines on Kafka and Redis, running as microservices behind an API gateway.",
     "What did the event schema registry document define?", "registry doc never claimed"),
    ("Frontend developer building React interfaces against internal APIs.",
     "What did the component library spec require?", "spec never claimed"),
    ("Owned the deploy tooling and improved throughput of the ingestion service fourfold.",
     "What did the release checklist include?", "checklist never claimed"),
    ("Wrote the reconciliation service in Java against a Postgres database.",
     "What did the reconciliation SOP prescribe?", "SOP never claimed"),
    ("Built a sourcing team of six and cut attrition in the first 90 days by half.",
     "What did the sourcing playbook recommend?", "playbook never claimed"),
    ("HRBP for a 400-person org.",
     "What did the workforce plan project?", "plan never claimed"),
    ("Led campus hiring, sourcing, interview coordination and joinee onboarding for 120 offers.",
     "What did the campus engagement calendar cover?", "calendar never claimed"),
    ("Owned attrition, engagement surveys and the onboarding programme.",
     "What did the attrition RCA deck conclude?", "deck never claimed"),
    ("Ran interview panels and reduced time to offer from 40 days to 22.",
     "What did the interviewer training deck cover?", "deck never claimed"),
    ("Carrying a quota of $1.2M ARR.",
     "What did your territory plan commit to?", "territory plan never claimed"),
    ("Coached four inside sales reps on closing technique",
     "What did the coaching curriculum document contain?", "curriculum never claimed"),
    ("Ran 40 user interviews to find the top three pain points before writing the PRD",
     "What did the research synthesis report conclude?",
     "the PRD is claimed; a synthesis report is not"),
]

INVENTED_CONDITION: list[tuple[str, str, str]] = [
    ("Led the escalation desk for a SaaS product.",
     "Describe an incident where a P1 breached the 30-minute response SLA.", "30-min SLA invented"),
    ("Cut first response time from 9 hours to under 2.",
     "How did you handle tickets that exceeded the 4-hour escalation cap?", "4-hour cap invented"),
    ("Ran the chat support queue.",
     "What did you do when concurrency went above 3 chats per agent?", "concurrency limit invented"),
    ("Owned resolution time for P1 issues.",
     "How often did you miss the 24-hour resolution target?", "24-hour target invented"),
    ("Reduced reopen rate by a third.",
     "What happened when reopens crossed the 5% threshold?", "5% threshold invented"),
    ("Wrote macros for the top ten issue types.",
     "How did you handle macros used in under 10% of tickets?", "10% usage floor invented"),
    ("Managed a support team of 12 covering chat support and email support for an e-commerce platform.",
     "What did you do when a queue passed the 50-ticket backlog limit?", "50-ticket limit invented"),
    ("Took escalation from tier 1 and tracked resolution time week over week.",
     "How did you treat cases older than 7 days?", "7-day age rule invented"),
    ("Customer success manager for 60 enterprise accounts, working mostly out of Freshdesk and email support.",
     "What did you do for accounts below the 70% health-score floor?", "health-score floor invented"),
    ("Managed a team of 35 agents across 4 pods with 4 senior associates reporting to me",
     "How did you handle a pod dropping below 90% adherence?", "90% adherence bar invented"),
    ("Managed rosters for 42 agents across three shifts",
     "What did you do when shrinkage went past 12%?", "12% shrinkage cap invented"),
    ("Ran weekly calibration with the quality team",
     "How did you treat auditors scoring outside the plus or minus 5% band?", "5% band invented"),
    ("Managed a team of 22 agents and ran the daily huddle",
     "What happened when an agent missed the 85% quality cut-off?", "85% cut-off invented"),
    ("Ran workforce planning for a 24x7 contact centre.",
     "How did you plan for the 80/20 service-level standard?", "80/20 standard invented"),
    ("Owned shrinkage and abandon rate for a 200-seat call centre in Gurgaon.",
     "What did you do when abandon rate breached 5%?", "5% abandon threshold invented"),
    ("Managed nesting batches for new hires on a night shift voice process before they moved to the production floor.",
     "How did you handle trainees below the 75% nesting pass mark?", "75% pass mark invented"),
    ("Improved CSAT from 78% to 92% in four quarters by redesigning the escalation workflow",
     "How did you respond to any week where CSAT fell under 85%?", "85% floor invented"),
    ("Brought AHT down from 8 minutes to 5 and kept occupancy above 85%.",
     "What did you do when AHT drifted above the 6-minute ceiling?", "6-minute ceiling invented"),
    ("Managed a team of 45 agents and consistently exceeded all CSAT targets",
     "How did you handle the 95% CSAT floor for the account?", "95% floor invented"),
    ("Delivered a 30% improvement in AHT through advanced process optimisation",
     "What did you do about processes still above the 7-minute limit?", "7-minute limit invented"),
    ("Drove a 30% improvement in CSAT scores across the entire process",
     "How did you handle the client's 90% CSAT contractual minimum?", "contractual minimum invented"),
    ("Held SLA attainment at 97% across four queues by rebuilding the roster model",
     "What did you do when a queue slipped under the 95% penalty threshold?", "penalty threshold invented"),
    ("Loan operations executive. Handled disbursement checks, credit memos and monthly reconciliation.",
     "How did you handle files breaching the 48-hour disbursement TAT?", "48-hour TAT invented"),
    ("Owned CASA growth, daily reconciliation and audit compliance for a metro branch.",
     "What did you do when reconciliation broke the same-day cut-off?", "same-day cut-off invented"),
    ("Ran KYC audits and reported exceptions to the risk committee.",
     "How did you treat exceptions open beyond 30 days?", "30-day rule invented"),
    ("Reviewed loan files for underwriting and cleared KYC exceptions before disbursement.",
     "What happened when a file exceeded the 3-exception limit?", "3-exception limit invented"),
    ("Processed insurance claims and mutual fund transactions at a bank's back office in Mumbai.",
     "How did you handle claims above the 5 lakh authority limit?", "authority limit invented"),
    ("Worked in NPA recovery for a housing finance company, coordinating with legal on more than 300 accounts.",
     "What did you do for accounts past the 50 lakh write-off threshold?", "write-off threshold invented"),
    ("Built ETL pipelines with dbt and Airflow, and maintained the reporting layer in SQL.",
     "How did you handle DAGs running longer than 2 hours?", "2-hour runtime rule invented"),
    ("Built dashboards in Tableau and Power BI on top of a Snowflake warehouse.",
     "What did you do when a dashboard took over 30 seconds to load?", "30-second budget invented"),
    ("Data engineer. Airflow DAGs, dbt models and a warehouse feeding Tableau extracts.",
     "How did you treat freshness beyond the 6-hour SLA?", "6-hour SLA invented"),
    ("Owned the SQL reporting stack and a Looker dashboard suite for the commercial team.",
     "What happened when query cost exceeded the monthly credit cap?", "credit cap invented"),
    ("Trained a demand forecast model and took it to production.",
     "How did you act when MAPE went above 15%?", "15% MAPE bar invented"),
    ("Wrote SQL against the data warehouse to produce weekly reporting for the operations group.",
     "What did you do when weekly reporting slipped past Tuesday noon?", "deadline invented"),
    ("Built REST APIs on Postgres and deployed to Kubernetes on AWS.",
     "How did you handle endpoints breaching the 200ms budget?", "200ms budget invented"),
    ("Cut p95 latency from 900ms to 180ms.",
     "What did you do when p99 exceeded 500ms?", "a DIFFERENT percentile and a new threshold"),
    ("Built event pipelines on Kafka and Redis, running as microservices behind an API gateway.",
     "How did you respond when consumer lag passed 10,000 messages?", "lag threshold invented"),
    ("Frontend developer building React interfaces against internal APIs.",
     "What did you do when bundle size crossed 250KB?", "size budget invented"),
    ("Owned the deploy tooling and improved throughput of the ingestion service fourfold.",
     "How did you handle deploys longer than the 15-minute window?", "deploy window invented"),
    ("Wrote the reconciliation service in Java against a Postgres database.",
     "What did you do when breaks exceeded 0.5% of volume?", "break tolerance invented"),
    ("Built a sourcing team of six and cut attrition in the first 90 days by half.",
     "How did you handle recruiters below the 4-hire quarterly bar?", "hiring bar invented"),
    ("HRBP for a 400-person org.",
     "What did you do when attrition passed the 18% annual cap?", "attrition cap invented"),
    ("Led campus hiring, sourcing, interview coordination and joinee onboarding for 120 offers.",
     "How did you handle campuses below the 60% conversion floor?", "conversion floor invented"),
    ("Ran interview panels and reduced time to offer from 40 days to 22.",
     "What did you do when a panel exceeded the 5-day feedback SLA?", "feedback SLA invented"),
    ("Owned the recruiting funnel from sourcing through offer rollout.",
     "How did you treat requisitions open beyond 45 days?", "45-day rule invented"),
    ("Carrying a quota of $1.2M ARR.",
     "What did you do in quarters where you fell below the 80% attainment floor?", "attainment floor invented"),
    ("Ran the deal desk.",
     "How did you handle discounts above the 20% approval threshold?", "approval threshold invented"),
    ("Deprioritised two epics to ship the MVP a quarter early.",
     "What did you do when an epic exceeded its 3-sprint budget?", "sprint budget invented"),
]

BLOCKS = {
    ("invented_tool", "specifically_unentailed"): SPECIFICALLY_UNENTAILED,
    ("invented_event", ""): INVENTED_EVENT,
    ("invented_metric", ""): INVENTED_METRIC,
    ("invented_artefact", ""): INVENTED_ARTEFACT,
    ("invented_condition", ""): INVENTED_CONDITION,
}


# ---------------------------------------------------------------------------
# Added after the mined candidates were hand-labelled.
#
# The miner found 75 `invented_outcome` candidates and 33 `invented_event`
# candidates. Under the decision rules only 9 and 4 survive: the rest are
# nominalisations the question legitimately introduces ("the success", "the
# impact") or the claim's own movement in other words ("the latency reduction"
# on a claim that says "Cut p95 latency from 900ms to 180ms"). That collapse is
# the single most important number in this study, and it is also why these two
# sub-types need so many constructed positives.
# ---------------------------------------------------------------------------

INVENTED_OUTCOME: list[tuple[str, str, str]] = [
    ("Managed a team of 22 agents and ran the daily huddle",
     "How did you sustain the productivity gain the huddles produced?", "gain asserted"),
    ("Managed a team of 35 agents across 4 pods with 4 senior associates reporting to me",
     "What caused the drop in escalations after you restructured the pods?", "drop asserted"),
    ("Managed rosters for 42 agents across three shifts",
     "How did you verify the improvement in coverage?", "improvement asserted"),
    ("Ran weekly calibration with the quality team",
     "How did you measure the lift in audit scores after calibration?", "lift asserted"),
    ("Ran workforce planning for a 24x7 contact centre.",
     "What drove the reduction in overtime?", "reduction asserted"),
    ("Owned shrinkage and abandon rate for a 200-seat call centre in Gurgaon.",
     "How did you confirm the abandon-rate improvement held?", "improvement asserted"),
    ("Owned shrinkage and occupancy for a 150-seat process, reporting the numbers through the daily huddle.",
     "What explains the occupancy gain over the year?", "gain asserted"),
    ("Managed nesting batches for new hires on a night shift voice process before they moved to the production floor.",
     "How did you measure the improvement in new hires' confidence?", "improvement asserted"),
    ("Managed a team of 45 agents and consistently exceeded all CSAT targets",
     "How did you sustain the year-on-year CSAT increase?", "an increase, not just attainment"),
    ("Ran the chat support queue.",
     "What caused the fall in queue wait times?", "fall asserted"),
    ("Led the escalation desk for a SaaS product.",
     "How did you measure the reduction in repeat escalations?", "reduction asserted"),
    ("Owned resolution time for P1 issues.",
     "How did you verify the improvement in P1 resolution?", "improvement asserted"),
    ("Wrote macros for the top ten issue types.",
     "How did you measure the handle-time savings the macros produced?", "savings asserted"),
    ("Took escalation from tier 1 and tracked resolution time week over week.",
     "What drove the week-on-week improvement?", "improvement asserted; tracking is not improving"),
    ("Customer success manager for 60 enterprise accounts, working mostly out of Freshdesk and email support.",
     "How did you measure the renewal uplift across your book?", "uplift asserted"),
    ("Managed a support team of 12 covering chat support and email support for an e-commerce platform.",
     "What caused the improvement in first-contact resolution?", "improvement asserted"),
    ("Ran KYC audits and reported exceptions to the risk committee.",
     "How did you measure the fall in audit exceptions?", "fall asserted; the claim only reports them"),
    ("Reviewed loan files for underwriting and cleared KYC exceptions before disbursement.",
     "How did you confirm the reduction in rework?", "reduction asserted"),
    ("Loan operations executive. Handled disbursement checks, credit memos and monthly reconciliation.",
     "What drove the improvement in disbursement turnaround?", "improvement asserted"),
    ("Owned CASA growth, daily reconciliation and audit compliance for a metro branch.",
     "How did you measure the reduction in reconciliation breaks?", "reduction asserted"),
    ("Processed insurance claims and mutual fund transactions at a bank's back office in Mumbai.",
     "How did you verify the accuracy gain after the process change?", "gain and change both asserted"),
    ("Worked in NPA recovery for a housing finance company, coordinating with legal on more than 300 accounts.",
     "How did you measure the improvement in recovery rate?", "improvement asserted"),
    ("Built ETL pipelines with dbt and Airflow, and maintained the reporting layer in SQL.",
     "How did you measure the reduction in pipeline runtime?", "reduction asserted"),
    ("Built dashboards in Tableau and Power BI on top of a Snowflake warehouse.",
     "What drove the increase in dashboard adoption?", "increase asserted"),
    ("Data engineer. Airflow DAGs, dbt models and a warehouse feeding Tableau extracts.",
     "How did you confirm the drop in failed runs?", "drop asserted"),
    ("Owned the SQL reporting stack and a Looker dashboard suite for the commercial team.",
     "How did you measure the time saved for the commercial team?", "savings asserted"),
    ("Wrote SQL against the data warehouse to produce weekly reporting for the operations group.",
     "What caused the improvement in reporting turnaround?", "improvement asserted"),
    ("Trained a demand forecast model and took it to production.",
     "How did you measure the forecast accuracy improvement?", "improvement asserted"),
    ("Built REST APIs on Postgres and deployed to Kubernetes on AWS.",
     "How did you measure the performance improvement after deploying to AWS?",
     "improvement asserted (this one is OBSERVED in the corpus too)"),
    ("Built event pipelines on Kafka and Redis, running as microservices behind an API gateway.",
     "What explains the throughput gain after the migration?", "gain and migration asserted"),
    ("Frontend developer building React interfaces against internal APIs.",
     "How did you measure the improvement in user experience?", "improvement asserted"),
    ("Wrote the reconciliation service in Java against a Postgres database.",
     "How did you verify the reduction in manual effort?", "reduction asserted"),
    ("HR generalist handling payroll, onboarding and exit formalities for two business units.",
     "How did you measure the improvement in payroll accuracy?", "improvement asserted"),
    ("HRBP for a 400-person org.",
     "What drove the increase in engagement scores?", "increase asserted"),
    ("Led campus hiring, sourcing, interview coordination and joinee onboarding for 120 offers.",
     "How did you measure the improvement in joinee conversion?", "improvement asserted"),
    ("Owned the recruiting funnel from sourcing through offer rollout.",
     "How did you measure the reduction in drop-offs at offer stage?", "reduction asserted"),
    ("Sourcing on Naukri and Shine, managed offer rollout and joinee follow-up.",
     "What caused the improvement in offer acceptance?", "improvement asserted"),
    ("Ran the deal desk.",
     "How did you measure the margin improvement the deal desk delivered?", "improvement asserted"),
    ("Pricing approvals, quota planning and revenue forecast reviews for the field sales org.",
     "How did you verify the increase in forecast accuracy?", "increase asserted"),
    ("Ran discovery interviews with branch staff.",
     "How did you measure the improvement in branch satisfaction?", "improvement asserted"),
    ("Built the experiment backlog and instrumented activation events across the funnel.",
     "What drove the lift in activation after instrumentation?", "lift asserted"),
]

INVENTED_EVENT_MORE: list[tuple[str, str, str]] = [
    ("Managed a team of 22 agents and ran the daily huddle",
     "How did you handle the huddle that turned into a grievance session?", "definite episode"),
    ("Ran weekly calibration with the quality team",
     "What did you do about the calibration dispute with the client auditor?", "definite dispute"),
    ("Ran workforce planning for a 24x7 contact centre.",
     "How did you cover the night shift after the mass sick-out?", "definite sick-out"),
    ("Owned shrinkage and abandon rate for a 200-seat call centre in Gurgaon.",
     "What did you do during the power failure that emptied the floor?", "definite failure"),
    ("Owned shrinkage and occupancy for a 150-seat process, reporting the numbers through the daily huddle.",
     "How did you respond to the client's escalation about occupancy?", "definite escalation"),
    ("Managed nesting batches for new hires on a night shift voice process before they moved to the production floor.",
     "What did you do when the batch failed its go-live review?", "definite failure"),
    ("Managed a team of 45 agents and consistently exceeded all CSAT targets",
     "How did you handle the month CSAT collapsed?", "definite collapse, contradicting the claim"),
    ("Owned resolution time for P1 issues.",
     "What did you do during the multi-day outage?", "definite outage"),
    ("Wrote macros for the top ten issue types.",
     "How did you recover from the macro that sent the wrong reply to customers?", "definite error"),
    ("Customer success manager for 60 enterprise accounts, working mostly out of Freshdesk and email support.",
     "What did you do when the largest account threatened to churn?", "definite threat"),
    ("Managed a support team of 12 covering chat support and email support for an e-commerce platform.",
     "How did you handle the sale weekend that broke the queue?", "definite weekend"),
    ("Reviewed loan files for underwriting and cleared KYC exceptions before disbursement.",
     "What did you do after the fraudulent file got through?", "definite fraud"),
    ("Loan operations executive. Handled disbursement checks, credit memos and monthly reconciliation.",
     "How did you resolve the month-end reconciliation break?", "definite break"),
    ("Worked in NPA recovery for a housing finance company, coordinating with legal on more than 300 accounts.",
     "What did you do when the court stayed the recovery?", "definite ruling"),
    ("Built dashboards in Tableau and Power BI on top of a Snowflake warehouse.",
     "How did you handle the warehouse outage before the board meeting?", "two definite events"),
    ("Data engineer. Airflow DAGs, dbt models and a warehouse feeding Tableau extracts.",
     "What did you do about the backfill that corrupted the extracts?", "definite corruption"),
    ("Owned the SQL reporting stack and a Looker dashboard suite for the commercial team.",
     "How did you respond to the reporting error the CFO found?", "definite error and person"),
    ("Wrote SQL against the data warehouse to produce weekly reporting for the operations group.",
     "What did you do the week the report went out wrong?", "definite week"),
    ("Trained a demand forecast model and took it to production.",
     "How did you handle the model drift incident?", "definite incident"),
    ("Frontend developer building React interfaces against internal APIs.",
     "What did you do when the release broke the checkout page?", "definite breakage"),
    ("Wrote the reconciliation service in Java against a Postgres database.",
     "How did you deal with the database failover during month-end?", "definite failover"),
    ("HR generalist handling payroll, onboarding and exit formalities for two business units.",
     "What did you do about the payroll run that missed a business unit?", "definite miss"),
    ("Owned attrition, engagement surveys and the onboarding programme.",
     "How did you respond to the resignation wave in the second quarter?", "definite wave"),
    ("Owned the recruiting funnel from sourcing through offer rollout.",
     "What did you do when the hiring manager rejected the whole shortlist?", "definite rejection"),
    ("Carrying a quota of $1.2M ARR.",
     "How did you recover from the quarter you missed quota?", "definite miss"),
    ("Owned a pipeline of 80 prospects and hit quota six quarters running.",
     "What did you do when the biggest deal slipped out of the quarter?", "definite slip"),
    ("Coached four inside sales reps on closing technique",
     "How did you handle the rep who refused the coaching?", "definite refusal"),
    ("Built the experiment backlog and instrumented activation events across the funnel.",
     "What did you do when the experiment shipped with broken tracking?", "definite failure"),
    ("Arranged vendor contracts and dealt with escalations through the regional office.",
     "How did you handle the contract that lapsed?", "definite lapse"),
]

INVENTED_METRIC_MORE: list[tuple[str, str, str]] = [
    ("Managed a team of 35 agents across 4 pods with 4 senior associates reporting to me",
     "How did you measure pod-level utilisation?", "utilisation never claimed"),
    ("Managed rosters for 42 agents across three shifts",
     "How did you calculate roster efficiency?", "roster efficiency never claimed"),
    ("Ran weekly calibration with the quality team",
     "How did you measure inter-rater reliability?", "IRR never claimed"),
    ("Owned shrinkage and occupancy for a 150-seat process, reporting the numbers through the daily huddle.",
     "How did you compute your forecast accuracy?", "forecast accuracy never claimed"),
    ("Managed nesting batches for new hires on a night shift voice process before they moved to the production floor.",
     "How did you measure speed to competency?", "speed to competency never claimed"),
    ("Managed a team of 45 agents and consistently exceeded all CSAT targets",
     "How did you calculate your transfer rate?", "transfer rate never claimed"),
    ("Improved CSAT from 78% to 92% in four quarters by redesigning the escalation workflow",
     "How did you measure your customer effort score?", "CES is a different measure from CSAT"),
    ("Held SLA attainment at 97% across four queues by rebuilding the roster model",
     "How did you compute your forecast-to-actual variance?", "variance never claimed"),
    ("Ran discovery interviews with branch staff.",
     "How did you measure feature request frequency?", "frequency never claimed"),
    ("Ran 40 user interviews to find the top three pain points before writing the PRD",
     "How did you measure your interview saturation rate?", "saturation never claimed"),
    ("Deprioritised two epics to ship the MVP a quarter early.",
     "How did you measure your sprint predictability?", "predictability never claimed"),
    ("Ran daily stand-ups, tracked deliverables against milestones and presented to stakeholders every week.",
     "How did you measure your milestone slip rate?", "slip rate never claimed"),
    ("Drove client engagement through structured quarterly reviews with each account owner.",
     "How did you calculate client health scores?", "health score never claimed"),
    ("Handled vendor coordination, invoice follow-up and the daily MIS for the regional office.",
     "How did you measure invoice ageing?", "ageing never claimed"),
    ("Arranged vendor contracts and dealt with escalations through the regional office.",
     "How did you measure vendor SLA compliance?", "compliance measure never claimed"),
    ("Re-engineered the intake process and delivered rapid improvements in turnaround time.",
     "How did you calculate process cycle efficiency?", "PCE never claimed"),
]

BLOCKS[("invented_outcome", "")] = INVENTED_OUTCOME
BLOCKS[("invented_event", "")] = INVENTED_EVENT + INVENTED_EVENT_MORE
BLOCKS[("invented_metric", "")] = INVENTED_METRIC + INVENTED_METRIC_MORE
